language: generic
sudo: false
addons:
  apt:
    packages:
    - luarocks
before_install:
  - luarocks install --local luacheck
script: 
- $HOME/.luarocks/bin/luacheck --no-color ./mods
notifications:
  email: false
